name: "Validate Dev Container Templates"

on:
  pull_request:
    branches: [main]
    paths:
      - "src/**/devcontainer-template.json"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate templates
        uses: devcontainers/action@v1
        with:
          validate-only: "true"
